dumps:
  path: ../   # path to weights dir
  weights: weights                  # name of weights dir
  logs: logs                        # name of logs dir
  name_save: tt                     # name to save models

data:
  path: ../../../../raid/data/ibespalov/endocrinology/ # path to data directory
  train_images: ./   # dir to train images
  train_masks: ./    # dir to labels
  test_images: ../segment_stage2.csv #train_2folds.csv # dir to test
  folds: ./dataset.csv #../train_segmentation_1308.csv    # validation folds
  predictions_path: preds.csv # predictions name